# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "git submodule update -f --init && npm install postcss-cli && hugo --themesDir ../.."

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.82.1"
  HUGO_THEME = "ocsy"
  HUGO_ENV = "production"
